version: '2'
services:
  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
      KAFKA_OPTS: "-Dzookeeper.4lw.commands.whitelist=ruok"
    ports:
      - 22181:2181

  kafka:
    image: confluentinc/cp-kafka:latest
    depends_on:
      - zookeeper
    ports:
      - 19092:19092
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: HOST1://10.1.1.249:19092,HOST2://10.2.1.44:29092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: HOST1:PLAINTEXT,HOST2:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: HOST1 
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
